name: Post Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Push Latest Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Test
        run: make travis
        timeout-minutes: 60

      - name: Deploy OPA Release
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # TODO: Remove s3 bucket override
        #run: make deploy-travis
        run: make release-travis IMAGE_ORG=patrickeast

      - name: (Optional) Create Draft Release
        run: |
          set -x

          TAG_NAME="${GITHUB_REF##*/}"

          if hub release show "${TAG_NAME}" > /dev/null; then
            echo "Release already exists... skipping"
            exit 0
          fi

          # Create a draft release
          hub release create -m "${TAG_NAME}" --draft "${TAG_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}