name: Post Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Push Latest Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set TAG_NAME in Environment
        # Subsequent jobs will be have the computed tag name
        run: echo ::set-env name=TAG_NAME::"${GITHUB_REF##*/}"

      - name: Build Release Binaries
        run: make release VERSION=${TAG_NAME#v}

      # Steps below assume the bins are in the root of the repo, but make
      # release places them in a versioned directory
      # TODO: Refactor make targets to get them in sync?
      - name: Copy Relase Binaries
        run: cp ./_release/${TAG_NAME#v}/opa_* ./

      - name: Build and Deploy OPA Docker Images
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # TODO: Remove image org override
        #run: make deploy-travis
        run: make release-travis IMAGE_ORG=patrickeast

      - name: Create or Update Release
        run: ./build/github-release.sh
        env:
          # Required for the `hub` CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OPA Binaries
          path: opa_*