name: Push Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Push Latest Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Test
        run: make travis
        timeout-minutes: 20

      - name: Deploy OPA Release
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # TODO: Remove s3 bucket override
        #run: make deploy-travis
        run: make release-travis OPA_S3_RELEASE_BUCKET=test-opa-releases IMAGE_ORG=patrickeast

      - name: Create Draft Release
        run: |
          set -x

          TAG_NAME="${GITHUB_REF##*/}"

          if hub release show "${TAG_NAME}" > /dev/null; then
            echo "Release already exists... skipping"
            exit 0
          fi

          # Create a draft release
          hub release create -m "${TAG_NAME}" --draft "${TAG_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}