name: PR Check

on: [pull_request]

jobs:
  # TODO: We can split this into separate build, test, perf, and check jobs that
  # run in parallel to lower overall runtime of PR checks and give a nicer UI on
  # the reviews. See separate WASM step below for an example.
  go:
    name: Go
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Test Golang
        run: make travis-go
        timeout-minutes: 30

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OPA Binaries
          path: opa_*

  # WebAssembly build and tests workflow, can run independent of other workflows.
  wasm:
    name: WASM
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Test WASM
        run: make travis-wasm
        timeout-minutes: 15
